export const catalogCategories = [
  { id: "c1", name: "Audio", description: "Headphones, speakers and everything between.", color: "#E4572E", createdAt: Date.now() - 9e8 },
  {
    id: "c2",
    name: "Wearables",
    description: "Watches and cameras that earn their place on you.",
    color: "#5B6DFA",
    createdAt: Date.now() - 9e8,
  },
  {
    id: "c3",
    name: "Home & Desk",
    description: "Objects that make the desk feel like a place.",
    color: "#E9A13B",
    createdAt: Date.now() - 9e8,
  },
  { id: "c4", name: "Carry", description: "Bags and daily companions, built to be used.", color: "#3E8E5A", createdAt: Date.now() - 9e8 },
];
export const catalogProducts = [
  {
    id: "p1",
    name: "Aria One Headphones",
    sku: "FKN-AUD-001",
    categoryId: "c1",
    price: 249,
    stock: 24,
    stockThreshold: 8,
    rating: 4.8,
    image: "https://image.qwenlm.ai/public_source/1221a076-dd9b-48a8-acba-208f94fdb0db/195f0ac32-1e05-4aeb-ac5c-4f2715e7f256.png",
    tags: ["wireless", "anc"],
    featured: true,
    createdAt: Date.now() - 8e8,
    description: "Flagship over-ears with adaptive ANC, 40-hour battery and copper-detailed aluminium yokes. Tuned warm, built to last.",
  },
  {
    id: "p2",
    name: "Pulse S Smartwatch",
    sku: "FKN-WEA-002",
    categoryId: "c2",
    price: 199,
    stock: 18,
    stockThreshold: 6,
    rating: 4.6,
    image: "https://image.qwenlm.ai/public_source/1221a076-dd9b-48a8-acba-208f94fdb0db/1e61601a3-2379-4e97-8341-7b2145347719.png",
    tags: ["gps", "amoled"],
    featured: true,
    createdAt: Date.now() - 7e8,
    description:
      "A slim smartwatch with an AMOLED display, 10-day battery and dual-band GPS. Tracks workouts, sleep and nothing you don’t need.",
  },
  {
    id: "p3",
    name: "Orbit Mini Speaker",
    sku: "FKN-AUD-003",
    categoryId: "c1",
    price: 89,
    stock: 40,
    stockThreshold: 10,
    rating: 4.4,
    image: "https://image.qwenlm.ai/public_source/1221a076-dd9b-48a8-acba-208f94fdb0db/10a933344-3902-4fae-909d-b6ef032d577f.png",
    tags: ["360", "portable"],
    featured: false,
    createdAt: Date.now() - 6e8,
    description: "Pocketable 360° speaker with a fabric wrap and 14-hour runtime. Pairs instantly, survives the backpack.",
  },
  {
    id: "p4",
    name: "Halo Task Lamp",
    sku: "FKN-HOM-004",
    categoryId: "c3",
    price: 119,
    stock: 12,
    stockThreshold: 6,
    rating: 4.7,
    image: "https://image.qwenlm.ai/public_source/1221a076-dd9b-48a8-acba-208f94fdb0db/19dacd424-2135-436f-8436-768910775abe.png",
    tags: ["led", "dimmable"],
    featured: true,
    createdAt: Date.now() - 5e8,
    description: "A sculptural task lamp with stepless dimming and warm-to-cool spectrum. One-touch memory, zero flicker.",
  },
  {
    id: "p5",
    name: "Nomad 22L Backpack",
    sku: "FKN-CAR-005",
    categoryId: "c4",
    price: 148,
    stock: 15,
    stockThreshold: 5,
    rating: 4.9,
    image: "https://image.qwenlm.ai/public_source/1221a076-dd9b-48a8-acba-208f94fdb0db/15fbddfaa-ff75-4be1-a479-8a5ff3147953.png",
    tags: ["waxed", "laptop"],
    featured: true,
    createdAt: Date.now() - 4e8,
    description: "Waxed-canvas carryall with a padded 16-inch laptop sleeve and leather hardware. Weatherproof, cabin-friendly.",
  },
  {
    id: "p6",
    name: "Drift 65 Keyboard",
    sku: "FKN-HOM-006",
    categoryId: "c3",
    price: 159,
    stock: 9,
    stockThreshold: 5,
    rating: 4.5,
    image: "https://image.qwenlm.ai/public_source/1221a076-dd9b-48a8-acba-208f94fdb0db/1214494b1-608d-4fa9-b9b6-f8af10bc365c.png",
    tags: ["mechanical", "hot-swap"],
    featured: false,
    createdAt: Date.now() - 3e8,
    description: "Gasket-mounted 65% board with pre-lubed linear switches and hot-swap sockets. Ships tuned, sounds thocky.",
  },
  {
    id: "p7",
    name: "Vista 4K Action Cam",
    sku: "FKN-WEA-007",
    categoryId: "c2",
    price: 229,
    stock: 7,
    stockThreshold: 4,
    rating: 4.3,
    image: "https://image.qwenlm.ai/public_source/1221a076-dd9b-48a8-acba-208f94fdb0db/1d128becf-b894-47ea-a6f0-a92f9be09d6d.png",
    tags: ["4k60", "waterproof"],
    featured: false,
    createdAt: Date.now() - 2e8,
    description: "Rugged 4K60 action camera with magnetic mounts and a swappable battery door. Waterproof to 10 m without a case.",
  },
  {
    id: "p8",
    name: "Ember Travel Mug",
    sku: "FKN-CAR-008",
    categoryId: "c4",
    price: 34,
    stock: 60,
    stockThreshold: 12,
    rating: 4.6,
    image: "https://image.qwenlm.ai/public_source/1221a076-dd9b-48a8-acba-208f94fdb0db/14c11f570-57a1-4d6c-9614-4edb2a8b8d5c.png",
    tags: ["ceramic", "bamboo"],
    featured: false,
    createdAt: Date.now() - 1e8,
    description: "Double-wall ceramic mug with a bamboo lid. Keeps your pour-over hot through two meetings.",
  },
];
