export const STORAGE_KEYS = Object.freeze({
  products: "fikarnot_products",
  categories: "fikarnot_categories",
  users: "fikarnot_users",
  orders: "fikarnot_orders",
  cart: "fikarnot_cart_legacy",
  wishlist: "fikarnot_wishlist_legacy",
  customerCarts: "fikarnot_customer_carts",
  customerWishlists: "fikarnot_customer_wishlists",
  session: "fikarnot_session",
  reviews: "fikarnot_reviews",
  inventoryLog: "fikarnot_inventory_log",
  coupons: "fikarnot_coupons",
  recentlyViewed: "fikarnot_recently_viewed",
  customerNotifications: "fikarnot_customer_notifications",
  supportTickets: "fikarnot_support_tickets",
  returnRequests: "fikarnot_return_requests",
  comparison: "fikarnot_comparison",
  seeded: "fikarnot_seeded_v3",
});
